# Generated by Django 5.2.6 on 2025-10-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescribedmedication',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='prescribedmedication',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor_notes',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='issued_date',
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_name',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='PrescribedMedication',
        ),
    ]
