# Generated by Django 5.2.6 on 2025-10-22 14:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_patient_insurance_details'),
        ('medical_records', '0002_remove_prescribedmedication_medication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=200.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI')], max_length=20),
        ),
        migrations.DeleteModel(
            name='BillItem',
        ),
    ]
