# Generated by Django 5.2.6 on 2025-10-24 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_remove_bill_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
