# Generated by Django 5.2.6 on 2025-11-27 10:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_alter_service_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine_name',
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, help_text="General instructions (e.g., 'Drink plenty of water')", null=True),
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(help_text='e.g., 500mg', max_length=100)),
                ('frequency', models.CharField(blank=True, help_text='e.g., 1-0-1 (Morning-Noon-Night)', max_length=100, null=True)),
                ('duration', models.CharField(blank=True, help_text='e.g., 5 days', max_length=100, null=True)),
                ('instructions', models.CharField(blank=True, help_text='e.g., After food', max_length=200, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical_records.prescription')),
            ],
        ),
    ]
