# Generated by Django 5.2.6 on 2026-01-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_remove_prescription_dosage_and_more'),
        ('staff_management', '0009_alter_doctorleave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='services', to='staff_management.doctor'),
        ),
    ]
