# Generated by Django 5.2.6 on 2025-10-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], max_length=20),
        ),
    ]
