# Generated by Django 5.2.6 on 2025-10-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=6),
        ),
    ]
