# Generated by Django 5.2.6 on 2025-10-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clinicsettings_consultation_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicsettings',
            name='consultation_fee',
        ),
    ]
