# Generated by Django 5.2.6 on 2025-10-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='insurance_details',
        ),
    ]
