# Generated by Django 5.2.6 on 2025-10-23 15:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_patient_insurance_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2025, 10, 23), message='Date of birth cannot be in the future.')]),
        ),
    ]
