# Generated by Django 5.2.6 on 2025-10-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0002_remove_doctor_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_fee',
        ),
    ]
