# Generated by Django 5.2.6 on 2025-10-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0003_remove_doctor_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=6),
        ),
    ]
