# Generated by Django 5.2.6 on 2025-10-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0005_doctorleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
