# Generated by Django 5.2.6 on 2025-11-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0006_schedule_is_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day_of_week', 'shift']},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning (10 AM - 1 PM)'), ('Evening', 'Evening (5 PM - 10 PM)')], default='Morning', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('doctor', 'day_of_week', 'shift')},
        ),
    ]
