# Generated by Django 5.2.6 on 2026-01-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0008_doctorleave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorleave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=20),
        ),
    ]
